<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<!-- <groupId>a012d035-75b8-47c0-b907-5217ee60b70e</groupId> -->
	<artifactId>cicd-demo</artifactId>
	<version>1.0.15-SNAPSHOT</version>
	<packaging>mule-application</packaging>
	<name>cicd-demo</name>
    <parent>
		<groupId>a012d035-75b8-47c0-b907-5217ee60b70e</groupId>
		<artifactId>poc-parent-pom</artifactId>
		<version>1.0.0</version>
	</parent>
    <properties>
		<cloudhub.application.name>demo-cicd-api-${env}</cloudhub.application.name>
	</properties>
	<build>
		<plugins>
			<plugin>
				<groupId>org.mule.tools.maven</groupId>
				<artifactId>mule-maven-plugin</artifactId>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-clean-plugin</artifactId>
			</plugin>
		</plugins>
	</build>
	<dependencies>
		<dependency>
			<groupId>org.mule.connectors</groupId>
			<artifactId>mule-http-connector</artifactId>
			<classifier>mule-plugin</classifier>
		</dependency>
		<dependency>
			<groupId>org.mule.connectors</groupId>
			<artifactId>mule-sockets-connector</artifactId>
			<classifier>mule-plugin</classifier>
		</dependency>
	</dependencies>
	<distributionManagement>
        <repository>
            <id>Exchange2</id>
            <name>Exchange2 Repository</name>
            <url>https://maven.anypoint.mulesoft.com/api/v2/organizations/${parent.groupId}/maven</url>
            <layout>default</layout>
        </repository>
    </distributionManagement>
	<repositories>
		<repository>
            <id>Exchange2</id>
            <name>Exchange2 Repository</name>
            <url>https://maven.anypoint.mulesoft.com/api/v2/organizations/a012d035-75b8-47c0-b907-5217ee60b70/maven</url>
            <layout>default</layout>
        </repository>
    </repositories>
    <pluginRepositories>
        <pluginRepository>
            <id>Exchange2</id>
            <name>Exchange2 Repository</name>
            <url>https://maven.anypoint.mulesoft.com/api/v2/organizations/a012d035-75b8-47c0-b907-5217ee60b70/maven</url>
            <layout>default</layout>
        </pluginRepository>
    </pluginRepositories>
</project>
